name: EURUSD Predictor Bot

on:
   schedule:
     #- cron: "29 4-15 * * 1-5"   # runs every hour at minute 0
       - cron: "04 12 * * 1-5"
       
   workflow_dispatch:      # manual trigger

 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install requests || true

      - name: Run predictor script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python eurusd_predictor.py
